export default function applicationTypes() {
  return {
    SET_WALLET_ADDRESS: 'SET_WALLET_ADDRESS',
    SET_WEB3: 'SET_WEB3',
    SET_DEFAULT_REFERRER: 'SET_DEFAULT_REFERRER',
    SET_BNB_BALANCE: 'SET_BNB_BALANCE',
    SET_TOKEN_BALANCE: 'SET_TOKEN_BALANCE',
    SET_DEPOSIT_DATA: 'SET_DEPOSIT_DATA'
  }
}
